#!/usr/bin/env bash

set -ex

temp_dir=$(mktemp -d /tmp/rls.XXXXXX)

cd ${temp_dir}
wget -q https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-09-27/rust-analyzer-x86_64-unknown-linux-gnu.gz
gunzip rust-analyzer-x86_64-unknown-linux-gnu.gz
mv rust-analyzer-x86_64-unknown-linux-gnu ${HOME}/.cargo/bin/rust-analyzer
chmod +x ${HOME}/.cargo/bin/rust-analyzer

rm -rf ${temp_dir}
